"""Tema visual de Sueños Dorados Admin."""

from config import (
    COLOR_ALERTA,
    COLOR_BLANCO,
    COLOR_BORDE,
    COLOR_EXITO,
    COLOR_FONDO,
    COLOR_INFO,
    COLOR_PRIMARIO,
    COLOR_PRIMARIO_HOVER,
    COLOR_SECUNDARIO,
    COLOR_SIDEBAR,
    COLOR_TEXTO,
    COLOR_TEXTO_G,
)


class Tema:
    GOLD = COLOR_PRIMARIO
    GOLD_LIGHT = "#FFC766"
    GOLD_DARK = COLOR_PRIMARIO_HOVER

    BG_PRIMARY = COLOR_FONDO
    BG_SECONDARY = COLOR_BLANCO
    BG_SIDEBAR = COLOR_SIDEBAR
    BG_HOVER = COLOR_PRIMARIO
    BG_CARD = COLOR_BLANCO
    BG_INPUT = "#FCFCFD"
    BG_TABLE_HEAD = "#F8FAFC"

    TEXT_PRIMARY = COLOR_TEXTO
    TEXT_SECONDARY = COLOR_SECUNDARIO
    TEXT_MUTED = COLOR_TEXTO_G
    TEXT_ON_DARK = COLOR_BLANCO

    BORDER = COLOR_BORDE
    BORDER_SOFT = "#EAECF0"
    BORDER_FOCUS = COLOR_PRIMARIO

    SUCCESS = COLOR_EXITO
    WARNING = COLOR_PRIMARIO
    ERROR = COLOR_ALERTA
    INFO = COLOR_INFO

    SIDEBAR_WIDTH = 220
    SIDEBAR_COLLAPSED = 72

    RADIUS_SM = 8
    RADIUS_MD = 10
    RADIUS_LG = 12
    RADIUS_XL = 18



